name: whollet_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  core:
    path: external_packages/core
  data:
    path: external_packages/data
  whollet_extensions:
    path: external_packages/whollet_extensions
  whollet_environment:
    path: external_packages/whollet_environment
  whollet_loading_indicator:
    path: external_packages/whollet_loading_indicator


  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  flow_builder: ^0.0.9
  bloc_concurrency: ^0.2.2

  event_bus: ^2.0.0
  shared_preferences: ^2.2.1
  permission_handler: ^11.0.0

  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  firebase_crashlytics: ^3.3.6
  firebase_analytics: ^10.5.0
  flutter_local_notifications: ^15.1.1

  path: ^1.8.3
  path_provider: ^2.1.1
  gap: any
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/intro/

  fonts:
    - family: Titillium
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: assets/fonts/TitilliumWeb-Italic.ttf
          weight: 400
          style: italic







flutter_intl:
  enabled: true
  class_name: WholletLocalization
  main_locale: en
  arb_dir: lib/src/l10n
  output_dir: lib/src/l10n/generated
  use_deferred_loading: true
